# Generated by Django 6.1.1 on 2026-09-16 22:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='course',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='destination_country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='intake',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='university',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.CreateModel(
            name='AcademicRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('ssc', 'SSC'), ('hsc', 'HSC'), ('diploma', 'Diploma'), ('bachelor', 'Bachelor'), ('master', 'Master'), ('other', 'Other')], max_length=20)),
                ('institution', models.CharField(max_length=200)),
                ('subject_or_group', models.CharField(blank=True, max_length=150)),
                ('passing_year', models.PositiveIntegerField(blank=True, null=True)),
                ('result', models.CharField(blank=True, max_length=50)),
                ('certificate_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_records', to='students.studentprofile')),
            ],
        ),
    ]
