# Generated by Django 6.1.1 on 2026-09-16 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='drive_link',
            field=models.URLField(blank=True),
        ),
    ]
