# Generated by Django 6.1.1 on 2026-09-16 23:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_studentprofile_drive_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='current_status',
            field=models.CharField(choices=[('registered', 'Registered'), ('documents', 'Documents Collection'), ('verification', 'Documents Verification'), ('application', 'University Application'), ('offer', 'Offer Letter'), ('visa', 'Visa Processing'), ('completed', 'Completed')], default='registered', max_length=30),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='next_step',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='progress',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='TimelineEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('event_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline_events', to='students.studentprofile')),
            ],
            options={
                'ordering': ['-event_date'],
            },
        ),
    ]
