# Generated by Django 6.1.1 on 2026-09-17 03:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination_country', models.CharField(max_length=100)),
                ('university', models.CharField(max_length=200)),
                ('course', models.CharField(max_length=200)),
                ('intake', models.CharField(blank=True, max_length=100)),
                ('drive_link', models.URLField(blank=True)),
                ('current_status', models.CharField(choices=[('registered', 'Registered'), ('documents', 'Documents Collection'), ('verification', 'Documents Verification'), ('application', 'University Application'), ('offer', 'Offer Letter'), ('visa', 'Visa Processing'), ('completed', 'Completed')], default='registered', max_length=30)),
                ('progress', models.PositiveIntegerField(default=0)),
                ('next_step', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='students.studentprofile')),
            ],
            options={
                'ordering': ('-updated_at', '-created_at'),
            },
        ),
        migrations.AddField(
            model_name='document',
            name='application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='students.studentapplication'),
        ),
        migrations.AddField(
            model_name='timelineevent',
            name='application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timeline_events', to='students.studentapplication'),
        ),
    ]
