# Generated by Django 6.1.1 on 2026-09-27 21:23

from django.db import migrations, models


def normalize_existing_statuses(apps, schema_editor):
    StudentProfile = apps.get_model("students", "StudentProfile")
    StudentApplication = apps.get_model("students", "StudentApplication")
    progress_by_status = {
        "registered": 5,
        "verification": 20,
        "documents": 30,
        "professor_outreach": 30,
        "application": 40,
        "interview": 50,
        "offer": 90,
        "visa_processing": 95,
        "visa_approved": 100,
        "pre_departure": 100,
    }
    for model in (StudentProfile, StudentApplication):
        model.objects.filter(current_status="visa").update(current_status="visa_processing")
        model.objects.filter(current_status="completed").update(current_status="pre_departure")
        for status, progress in progress_by_status.items():
            model.objects.filter(current_status=status).update(progress=progress)


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_studentapplication_document_application_and_more'),
    ]

    operations = [
        migrations.RunPython(normalize_existing_statuses, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='studentapplication',
            name='current_status',
            field=models.CharField(choices=[('registered', 'Profile Registered'), ('verification', 'Profile Verification & File Preparation'), ('documents', 'Document Collection & Review'), ('professor_outreach', "Professor Outreach & Acceptance Process (For Master's/Research Programs)"), ('application', 'University Application In Progress'), ('interview', 'Interview Preparation / Interview Scheduled'), ('offer', 'Admission Offer & Official Documents Received'), ('visa_processing', 'Visa Application Processing'), ('visa_approved', 'Visa Approved'), ('pre_departure', 'Pre-Departure Preparation & Ready to Fly')], default='registered', max_length=30),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='current_status',
            field=models.CharField(choices=[('registered', 'Profile Registered'), ('verification', 'Profile Verification & File Preparation'), ('documents', 'Document Collection & Review'), ('professor_outreach', "Professor Outreach & Acceptance Process (For Master's/Research Programs)"), ('application', 'University Application In Progress'), ('interview', 'Interview Preparation / Interview Scheduled'), ('offer', 'Admission Offer & Official Documents Received'), ('visa_processing', 'Visa Application Processing'), ('visa_approved', 'Visa Approved'), ('pre_departure', 'Pre-Departure Preparation & Ready to Fly')], default='registered', max_length=30),
        ),
    ]
